### PR TITLE
chore: rust version update

### PR DESCRIPTION
**Pull request by helio-frota**
* Details https://github.com/trustification/guac-rs/issues/66#issuecomment-2141840727
* Also simplifies ci a bit removing unused configs

### CODE REVIEW

**Review by dejanb — APPROVED** [review]

**Comment by dejanb** [comment]
@helio-frota just wondering if we need direct dependency to `reqwest` if it's only used by `graphql-client`?

**Comment by helio-frota** [comment]
@dejanb good question... I have no idea

**Comment by helio-frota** [comment]
oh we are using it as well

```
➜  guac-rs git:(main) rg reqwest
Cargo.toml
21:reqwest = "0.11"

lib/Cargo.toml
11:graphql_client = { workspace = true, features = ["reqwest"] }
12:reqwest = { workspace = true, features = ["json"] }

lib/src/client/semantic/spog/mod.rs
30:use graphql_client::reqwest::post_graphql;

lib/src/client/intrinsic/certify_good/mod.rs
2:use graphql_client::reqwest::post_graphql;

lib/src/client/intrinsic/vulnerability/mod.rs
5:use graphql_client::reqwest::post_graphql;

lib/src/client/intrinsic/path/mod.rs
6:use graphql_client::reqwest::post_graphql;

lib/src/client/intrinsic/vuln_metadata/mod.rs
2:use graphql_client::reqwest::post_graphql;

lib/src/client/intrinsic/certify_bad/mod.rs
2:use graphql_client::reqwest::post_graphql;

lib/src/client/intrinsic/vuln_equal/mod.rs
6:use graphql_client::reqwest::post_graphql;

lib/src/client/intrinsic/package/mod.rs
3:use graphql_client::reqwest::post_graphql;

lib/src/client/mod.rs
14:    Http(#[from] reqwest::Error),
29:    pub(crate) client: reqwest::Client,
36:            client: reqwest::Client::new(),
41:    pub fn with_client(url: String, client: reqwest::Client) -> Self {

lib/src/client/intrinsic/mod.rs
5:use reqwest::{Client, IntoUrl};
```

**Comment by dejanb** [comment]
Thanks, I knew that would be too easy :)

**Pull request merged**
