### PR TITLE
test: some tests added for the cli part

### PR DESCRIPTION
**Pull request by helio-frota**
Related to #62

### CODE REVIEW

**Review by bobmcwhirter — APPROVED** [review]
Excellent!

**Comment by helio-frota** [comment]
Thanks!

> [!NOTE]
> `env!("CARGO_BIN_EXE_guac")`  thanks to this documentation https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates
> I found this a way to simulate the behavior of `assert_cmd` crate --> `Command::cargo_bin` without penalize the system-platform-specific situation.

> [!NOTE]  
> `assert_eq!` is from tokio ( we need to test async way because guac-cli is async ), and we end up with this bit weirdo status code checker style `assert_eq!(output.status.code(), Some(2));`

> [!NOTE]  
> Most of the business parts related to these tests (specifically) on the PR are already tested on the lib side, so things like this:  `.arg("--justification").arg("lgtm")` are not harmful as the tests in the PR are really focused on the CLI part. 

> [!TIP]
> We can see future improvements removing unused code and rethinking if we still need need some commands /  sub-commands, like `poll` and what are the plans with the collect-sub that apparently tries to connect with kafka.

:+1:

**Comment by dejanb** [comment]
Apologies for taking so long to merge

**Comment by helio-frota** [comment]
thanks @dejanb :+1:

**Pull request merged**
